/**
 * @fileoverview Aquarium-specific sensor presets
 * Default setpoints for freshwater aquarium — users can override per sensor.
 */

export const AQUARIUM_SENSORS = {
  temperature: {
    name: 'Temperature',
    unit: '°C',
    setpoint: 25,
    step: 1,
    mode: 'heatflow',
  },
  ph: {
    name: 'pH',
    unit: 'pH',
    setpoint: 7.0,
    step: 0.3,
    mode: 'centric',
    min_limit: 0,
  },
  ammonia: {
    name: 'Ammonia',
    unit: 'ppm',
    setpoint: 0,
    step: 0.25,
    mode: 'centric',
    min_limit: 0,
  },
  nitrite: {
    name: 'Nitrite',
    unit: 'ppm',
    setpoint: 0,
    step: 0.25,
    mode: 'centric',
    min_limit: 0,
  },
  nitrate: {
    name: 'Nitrate',
    unit: 'ppm',
    setpoint: 20,
    step: 10,
    mode: 'centric',
    min_limit: 0,
  },
  gh: {
    name: 'General Hardness',
    unit: 'dGH',
    setpoint: 8,
    step: 2,
    mode: 'centric',
    min_limit: 0,
  },
  kh: {
    name: 'Carbonate Hardness',
    unit: 'dKH',
    setpoint: 6,
    step: 1,
    mode: 'centric',
    min_limit: 0,
  },
  co2: {
    name: 'CO2',
    unit: 'mg/L',
    setpoint: 20,
    step: 5,
    mode: 'centric',
    min_limit: 0,
  },
  phosphate: {
    name: 'Phosphate',
    unit: 'ppm',
    setpoint: 0.5,
    step: 0.25,
    mode: 'centric',
    min_limit: 0,
  },
  salinity: {
    name: 'Salinity',
    unit: 'ppt',
    setpoint: 0,
    step: 1,
    mode: 'centric',
    min_limit: 0,
  },
  specific_gravity: {
    name: 'Specific Gravity',
    unit: 'sg',
    setpoint: 1.025,
    step: 0.002,
    mode: 'centric',
  },
  calcium: {
    name: 'Calcium',
    unit: 'ppm',
    setpoint: 420,
    step: 20,
    mode: 'centric',
    min_limit: 0,
  },
  magnesium: {
    name: 'Magnesium',
    unit: 'ppm',
    setpoint: 1300,
    step: 50,
    mode: 'centric',
    min_limit: 0,
  },
  alkalinity: {
    name: 'Alkalinity',
    unit: 'dKH',
    setpoint: 8,
    step: 1,
    mode: 'centric',
    min_limit: 0,
  },
  water_level: {
    name: 'Water Level',
    unit: '%',
    setpoint: 100,
    step: 5,
    mode: 'centric',
    min_limit: 0,
  },
};
